name: Checklist

on:
  pull_request:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const path = require('path')
            const child_process = require('child_process')
            const __dirname = path.resolve(path.dirname(''));
            const ls = child_process.execSync('ls').toString();
            // await github.issues.createComment({...context.issue, body: fs.readFileSync(`${__dirname}/checklist.md`, 'utf8')})
            // await github.issues.createComment({...context.issue, body: ls.toString() })
