name: Checklist

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            await github.issues.createComment({...context.issue, body: fs.readFileSync('./checklist.md', 'utf8')})
